global:
  imageRegistry: "company-registry/"

# Consider this Image tag Mainly. But considers global imageRegistry, if set by parent chart.
image:
  registry: docker.io
  repository: bitnami/apache

templates:
  - |
      apiVersion: v1
      kind: Pod
      metadata:
        name: static-web
        labels:
          role: myrole
      spec:
        containers:
          - name: web
            image: {{ include "lib.utils.globals.image" (dict "image" .Values.image "context" $ ) }}
            ports:
              - name: web
                containerPort: 80
                protocol: TCP
