## Common Labels
# commonLabels -- Common Labels are added to each kubernetes resource manifest.
commonLabels: {}

## Overwrite Labels
# overwriteLabels -- Overwrites default labels, but not resource specific labels and common labels
overwriteLabels: {}

## Define Pure kubernetes resources
# resources -- Define resources to be deployed by the raw chart
resources: []
#
#  - apiVersion: scheduling.k8s.io/v1beta1
#    kind: PriorityClass
#    metadata:
#      name: common-critical
#    value: 100000000
#    globalDefault: false
#    description: "This priority class should only be used for critical priority common pods."
#
#  - apiVersion: scheduling.k8s.io/v1beta1
#    kind: PriorityClass
#    metadata:
#      name: common-high
#    value: 90000000
#    globalDefault: false
#    description: "This priority class should only be used for high priority common pods."
#

# templates -- Define templates which will be executed using the `tpl` function
templates: []
