{{- if (include "kubernetes.enabled" $) -}}
  {{- $kubernetes := $.Values.kubernetes -}}
  {{- if $kubernetes.etcd.enabled }}
    {{- $fullName := include "kubernetes.fullname" . -}}
    {{- $certName := include "kubernetes.certname" . -}}
    {{- $component_name := "etcd" -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-etcd-ca"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ $.Release.Namespace }}
spec:
  commonName: "{{ $certName }}-etcd-ca"
  secretName: "{{ $fullName }}-pki-etcd-ca"
  duration: 87600h # 3650d
  renewBefore: 8760h # 365d
  subject:
    organizations:
    - "{{ $fullName }}"
  usages:
  - "signing"
  - "key encipherment"
  - "cert sign"
  isCA: true
  issuerRef:
    {{- include "pkg.components.certificates.issuer" $ | nindent 4 }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "{{ $fullName }}-etcd-issuer"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ $.Release.Namespace }}
spec:
  ca:
    secretName: "{{ $fullName }}-pki-etcd-ca"
---
{{- $svcName1 := printf "%s-etcd" $fullName }}
{{- $svcName2 := printf "%s-etcd.%s" $fullName .Release.Namespace }}
{{- $svcName3 := printf "%s-etcd.%s.svc" $fullName .Release.Namespace }}
{{- $podName1 := printf "*.%s-etcd" $fullName }}
{{- $podName2 := printf "*.%s-etcd.%s" $fullName .Release.Namespace }}
{{- $podName3 := printf "*.%s-etcd.%s.svc" $fullName .Release.Namespace }}
{{- $svcClientName1 := printf "%s-etcd-client" $fullName }}
{{- $svcClientName2 := printf "%s-etcd-client.%s" $fullName .Release.Namespace }}
{{- $svcClientName3 := printf "%s-etcd-client.%s.svc" $fullName .Release.Namespace }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-etcd-peer"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ $.Release.Namespace }}
spec:
  commonName: "{{ $certName }}-etcd-peer"
  secretName: "{{ $fullName }}-pki-etcd-peer"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  subject:
    organizations:
    - "{{ $fullName }}"
  usages:
  - "signing"
  - "key encipherment"
  - "server auth"
  - "client auth"
  dnsNames:
  - "{{ $svcName1 }}"
  - "{{ $svcName2 }}"
  - "{{ $svcName3 }}"
  - "{{ $podName1 }}"
  - "{{ $podName2 }}"
  - "{{ $podName3 }}"
  - "localhost"
  ipAddresses:
  - "127.0.0.1"
  issuerRef:
    name: "{{ $fullName }}-etcd-issuer"
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-etcd-server"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ $.Release.Namespace }}
spec:
  commonName: "{{ $certName }}-etcd-server"
  secretName: "{{ $fullName }}-pki-etcd-server"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  subject:
    organizations:
    - "{{ $fullName }}"
  usages:
  - "signing"
  - "key encipherment"
  - "server auth"
  - "client auth"
  dnsNames:
  - "{{ $svcName1 }}"
  - "{{ $svcName2 }}"
  - "{{ $svcName3 }}"
  - "{{ $podName1 }}"
  - "{{ $podName2 }}"
  - "{{ $podName3 }}"
  - "{{ $svcClientName1 }}"
  - "{{ $svcClientName2 }}"
  - "{{ $svcClientName3 }}"
  - "localhost"
  {{- with $kubernetes.etcd.certSANs.dnsNames }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  ipAddresses:
  - "127.0.0.1"
  {{- with $kubernetes.etcd.service.loadBalancerIP }}
  {{- if not (has . $kubernetes.etcd.certSANs.ipAddresses) }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- with $kubernetes.etcd.certSANs.ipAddresses }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  issuerRef:
    name: "{{ $fullName }}-etcd-issuer"
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-etcd-healthcheck-client"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ $.Release.Namespace }}
spec:
  commonName: "{{ $certName }}-etcd-healthcheck-client"
  secretName: "{{ $fullName }}-pki-etcd-healthcheck-client"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  subject:
    organizations:
    - "system:masters"
  usages:
  - "signing"
  - "key encipherment"
  - "client auth"
  issuerRef:
    name: "{{ $fullName }}-etcd-issuer"
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-apiserver-etcd-client"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ $.Release.Namespace }}
spec:
  commonName: "{{ $certName }}-apiserver-etcd-client"
  secretName: "{{ $fullName }}-pki-apiserver-etcd-client"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  subject:
    organizations:
    - "system:masters"
  usages:
  - "signing"
  - "key encipherment"
  - "client auth"
  issuerRef:
    name: "{{ $fullName }}-etcd-issuer"
    kind: Issuer
  {{- end }}
{{- end }}
