apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config_data.secrets.files.name }}
data:
  {{- range .Values.config_data.secrets.files.items }}
    {{- .name | nindent 2 }}: | {{- include "isString" .content | b64enc | nindent 4 }}
  {{- end }}