apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config_data.secrets.strings.name }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.config_data.secrets.strings.items }}
    {{- $key | nindent 2 }}: {{ $val }}
  {{- end -}}

