{{- if (include "autoscaler.enabled" $) -}}
  {{- $manifest := $.Values.autoscaler -}}
  {{- if $manifest.podDisruptionBudget -}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "autoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "autoscaler.labels" . | nindent 4 }}
spec: {{- toYaml $manifest.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels: {{- include "autoscaler.selectorLabels" . | nindent 6 }}
  {{- end -}}
{{- end -}}
