{{- define "common.controller.envSecret" -}}
{{- $root := . }}
{{- range $componentName, $componentValues := .Values.components }}
{{- if $componentValues.controller }}
{{- if $componentValues.controller.deploy }}
{{- if or $componentValues.controller.containers $componentValues.controller.initContainers }}
{{- $containers := merge ($componentValues.controller.containers | default dict) ($componentValues.controller.initContainers | default dict) }}
{{- range $containerName, $containerValues := $containers }}
{{- $secret := $containerValues.envSecret }}
{{- if $secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "library.name" $root }}-{{ $componentName }}-{{ $containerName }}
  labels:
{{ include "library.labels.standard" $root | indent 4 }}
    app.kubernetes.io/component: {{ $componentName }}-{{ $containerName }}
type: Opaque
data:
{{- range $key, $value := $secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
