{{- define "common.servicemonitor.secret" -}}
{{- if .Values.servicemonitor }}
{{- if and (.Values.servicemonitor.deploy) (.Values.servicemonitor.basicAuth.enabled) (empty .Values.servicemonitor.basicAuth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "library.name" . }}-metrics-credentials
  labels:
{{ include "library.labels.standard" . | indent 4 }}
data:
{{- range $key, $value := .Values.servicemonitor.basicAuth.newSecret }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
type: Opaque
{{- end }}
{{- end }}
{{- end -}}
