{{- if (include "kubernetes.enabled" $) -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pkg.cluster.admin.cfg" $ }}
  labels: 
    {{- include "kubernetes.labels" $ | nindent 4 }}
data:
  admin.conf: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /pki/admin-client/ca.crt
        server: {{ include "kubernetes.api.url" $ }}
      name: default-cluster
    contexts:
    - context:
        cluster: default-cluster
        namespace: default
        user: default-auth
      name: default-context
    current-context: default-context
    kind: Config
    preferences: {}
    users:
    - name: default-auth
      user:
        client-certificate: /pki/admin-client/tls.crt
        client-key: /pki/admin-client/tls.key
{{- end -}}
