kind: Job
apiVersion: batch/v1
metadata:
  name: fullnameoverride
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fullnameoverride
    app.kubernetes.io/version: 0.0.0
    common.label: "1"
spec:
  template:
    metadata:
      name: test
      labels:
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: fullnameoverride
        common.label: "1"
    spec:
      imagePullSecrets:
      - name: private-registry
      - name: private-registry-group
      serviceAccountName: default
      restartPolicy: "Never"
      containers:
        -
          name: manifests-testing
          image: company-registry.example.com/bitnami/nginx:10.1.2.3
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
