{{- if (include "kubernetes.enabled" $) -}}
  {{- $kubernetes := $.Values.kubernetes -}}
  {{- if $kubernetes.scheduler.enabled }}
    {{- $fullName := include "kubernetes.fullname" . -}}
    {{- $component_name := "scheduler" -}}
    {{- $manifest := $kubernetes.scheduler.autoscaling -}}
    {{- if $manifest.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ $fullName }}-scheduler"
  labels: {{- include "kubernetes.labels" $ | nindent 4 }}
    {{ include "pkg.common.labels.component" $ }}: {{ $component_name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ $fullName }}-scheduler"
  minReplicas: {{ $manifest.minReplicas }}
  maxReplicas: {{ $manifest.maxReplicas }}
  metrics:
      {{- if $manifest.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare "<1.23-0" (include "pkg.utils.kubeVersion" .) }}
        targetAverageUtilization: {{ $manifest.targetCPUUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ $manifest.targetCPUUtilizationPercentage }}
        {{- end }}
      {{- end }}
      {{- if $manifest.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare "<1.23-0" (include "pkg.utils.kubeVersion" .) }}
        targetAverageUtilization: {{ $manifest.targetMemoryUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ $manifest.targetMemoryUtilizationPercentage }}
        {{- end }}
      {{- end }}
    {{- end -}}
  {{- end -}}
{{- end -}}
