## Reference: https://github.com/DylanVann/check-pull-request-title
---
name: 'PR Labels'
on: 
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.4.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"




