## Reference: https://github.com/DylanVann/check-pull-request-title
---
name: 'PR Validation'
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: dylanvann/check-pull-request-title@master
        with:
          # Match pull request titles in the form: `[chart]: Changed Something`
          pattern: '^\[[a-zA-Z\,\_\-]+\]\:.+'