## Reference: https://github.com/DylanVann/check-pull-request-title
---
name: 'Pull Request Validation'
on: 
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.4.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.5.0
        with:
          title-regex: "^\[[a-zA-Z\,\_\-]+\]\:.+"
          on-failed-regex-fail-action: false
          on-failed-regex-request-changes: false
          on-failed-regex-create-review: true
          on-failed-regex-comment:
            "Pull Request validation failed `%regex%`!"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"



