#
# Reference: https://github.com/helm/chart-testing-action
#
name: Helm Chart Linting and Testing
on: pull_request
jobs: 
  chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup Chart Linting
        id: lint
        uses: helm/chart-testing-action@v2.0.1

      - name: List changed charts
        id: list-changed
        run: |
          ## If executed with debug this won't work anymore.
          changed=$(ct --config ./ct.yaml list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
            echo "::set-output name=changed_charts::$changed"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config ./ct.yaml 

      - name: Run helm-docs (docs)
        run: | 
          for chart in ${CHANGED_CHARTS}; do
            echo "checking chart $chart"
            shasum ${chart%/}/README.md
          done

        env: 
          CHANGED_CHARTS: "${{ steps.list-changed.outputs.changed_charts }}"
        if: steps.list-changed.outputs.changed == 'true'  

      - name: Run unit-testing
        run: echo "${CHANGED_CHARTS}"
        env: 
          CHANGED_CHARTS: "${{ steps.list-changed.outputs.changed_charts }}"
        if: steps.list-changed.outputs.changed == 'true'  

      - name: Create kind cluster
        uses: helm/kind-action@v1.1.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config ./ct.yaml
        if: steps.list-changed.outputs.changed == 'true'        

  dry-release:
    runs-on: ubuntu-latest
    needs:
      - chart-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Helm Chart Publish
        uses: buttahtoast/helm-release-action@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dryrun: true
